### ISSUE TITLE
Some minor issues in GNOME 3.36

### ISSUE THREAD

**Issue by super-cooper** [Joshaby/Adapta-Colorpack#2]
Hi! Thank you for your work in keeping the Adapta project alive. It's my favorite theme by far, and there's nothing else quite like it. There are presently a few issues with GNOME 3.36 that I am experiencing on Debian Bullseye that you may be aware of. 

There are currently red circles around the 'X' button for GTK windows. This red circle should only appear when the button is hovered-over, and I believe should be larger than its present size

![image](https://user-images.githubusercontent.com/14908880/81087300-8937e800-8ec7-11ea-8ebe-fa7760713635.png)

It also seems the calendar widget in the dash is a little buggy, as most of it is themed, but not all, and the highlight when it is selected appears to be blue even though the theme I am using is cyan.

![image](https://user-images.githubusercontent.com/14908880/81087478-c69c7580-8ec7-11ea-8be8-6db1465491ae.png)

The 'X' icon in the overview also appears to be drawn twice, with one icon very slightly overlapping the other.

![image](https://user-images.githubusercontent.com/14908880/81087846-2f83ed80-8ec8-11ea-8a56-327d7ab6a342.png)

For now, this is all I've noticed. I can add more bugs to this issue if I see them.

**Comment by Joshaby** [comment]
Hi, thank you very much for your attention, I implemented this new layout of the X button on the window, it was one of the things I had been trying to do and I got it!  Gnome 3.36 gave me a bit of a headache, when I went to edit the theme (this on Pop OS) it mixed the themes, where I couldn't change, where I got a little lost, the wrong things I saw in Gnome were the same things that  you showed me, calendar with weird layout and this mixture of two X buttons from the window!  I don't know if it can be Gnome or my theme!

**Comment by Joshaby** [comment]
Hey man, I fixed the calendar popup problem, the double X button problem, I still don't know much about it, since old versions of gnome, there was this error!

tomorrow, I will post all versions of the theme with the modification

Images below
![Screenshot from 2020-05-07 19-34-34](https://user-images.githubusercontent.com/56325844/81337408-745f7e00-909a-11ea-89b3-4914436ce05c.png)
![Screenshot from 2020-05-07 19-34-44](https://user-images.githubusercontent.com/56325844/81337460-89d4a800-909a-11ea-8354-cf8a5756c3e3.png)

**Comment by super-cooper** [comment]
Wow, looks amazing! Thank you for your work <3

**Comment by Joshaby** [comment]
I found the double X button error, there are three commands for set layout of window button in activities mode, i removed these three commands, and this error has disarpeared! Tomorrow, i will post a new color of theme and with this error fixed!
