### ISSUE TITLE
Adapta UI feedback on Cinnamon

### ISSUE THREAD

**Issue by densha** [Joshaby/Adapta-Colorpack#3]
Hi @Joshaby 
I'm creating a post to follow up on feedback I created for the Cinnamon Spice fork adapta.

On Cinnamon, the shade of the grey indicator line is too similar to the black menu bar. I suggest a lighter shade to contrast the black from the grey. The grey line is very difficult to see for a lot of users - especially if you have settings to decrease the amount of blue light.

As an alternative suggestion, you can also try slightly increasing the line thickness. The grey line can be difficult to see since it's on the edge of the screen.

**Comment by Joshaby** [comment]
Hi man, making the lighter gray is better, in my opinion, to increase its area, it is strange!

current configuration
![Captura de tela de 2020-05-21 10-03-51](https://user-images.githubusercontent.com/56325844/82561882-8afdde80-9b4a-11ea-9956-42206f271407.png)

new configurarion
![Captura de tela de 2020-05-21 10-04-25](https://user-images.githubusercontent.com/56325844/82561931-a668e980-9b4a-11ea-8d09-c8e4614888e7.png)

Open the images in new tab, for better visualization

**Comment by densha** [comment]
@Joshaby the lighter grey looks good to me! Thanks for the help!
