### ISSUE TITLE
A few minor issues with the latest release

### ISSUE THREAD

**Issue by super-cooper** [Joshaby/Adapta-Colorpack#7]
Hi! I just wanted to report a few very minor issues with the shell theme on the latest release.

I am using the Cyan version, but when I click on the calendar widget, it is highlighted in a deep blue: 

![image](https://user-images.githubusercontent.com/14908880/102636759-0d6f7080-4123-11eb-9fb1-781fedd33442.png)

If I click on other icons, like the system tray, it is highlighted with the correct cyan color:

![image](https://user-images.githubusercontent.com/14908880/102636838-2546f480-4123-11eb-85b6-ab61caf4c657.png)

Also, the calender events and world clocks sections of the calendar widget are not shaded the correct color of grey:

![image](https://user-images.githubusercontent.com/14908880/102637013-5de6ce00-4123-11eb-8efb-1e9f3aa1350f.png)

And finally, the toggle switch for do not disturb mode appears to be from a different theme as well:

![image](https://user-images.githubusercontent.com/14908880/102637084-7820ac00-4123-11eb-8e1b-b6675d224fae.png)

Thanks you so much for keeping my favorite shell theme alive :)

**Comment by Joshaby** [comment]
Hi, I started to fix these problems, I had no idea they existed

**Comment by Joshaby** [comment]
![Captura de tela de 2021-01-03 14-51-48](https://user-images.githubusercontent.com/56325844/103485180-4a01c400-4dd3-11eb-8705-8fa90afe9662.png)
Hi, there is a little of my work! The normal version is almost finished!

**Comment by super-cooper** [comment]
José you are wonderful!

**Comment by Joshaby** [comment]
Bugs resolved!

**Comment by super-cooper** [comment]
Thank you 😄
